### ISSUE TITLE
Put export for BitString.js back in

### ISSUE THREAD

**Issue by mattcollier** [digitalbazaar/vc-revocation-list#15]
removal of this API was a breaking change but was released in v1.1.0.  v1.1.0 needs to be patched to put that export back in.  The export will be exporting the Class from the new module @digitalbazaar/bitstring

Once that's patched, that export should be removed and we should make a 2.0 release.

**Comment by mandyvenables** [comment]
`Bitstring` was put back in for v1.1.1 and removed as a breaking change in v2.0.0
