### ISSUE TITLE
TypeError: Bitstring is not a constructor

### ISSUE THREAD

**Issue by tc-developer01** [digitalbazaar/vc-revocation-list#25]
Hello,

I have installed vc-revocation-list via `npm install digitalbazaar/vc-revocation-list` and tried to create a revocation list in my TypeScript project:

```
import * as vcRevocationList from 'vc-revocation-list';
const list = await vcRevocationList.createList({ length: 100000 });
```

Which results in the following error:
```
TypeError: Bitstring is not a constructor
    at new RevocationList (node_modules/vc-revocation-list/RevocationList.js:8:22)
    at Object.createList (node_modules/vc-revocation-list/main.js:13:10)
```

I have tried installing and importing `@digitalbazaar/bitstring` directly:

```
import Bitstring from '@digitalbazaar/bitstring';
const bitstring = new Bitstring({length: 100000, buffer: null});
```

Which results in a very similar error:
```
TypeError: bitstring_1.default is not a constructor
```

Does someone know what causes this error and how to resolve it?

Thank you very much!

**Comment by dmitrizagidulin** [comment]
Hi @tc-developer01,
Thanks for the heads up. 
I suspect this has to do with our TypeScript woes, as described in this issue here - https://github.com/digitalbazaar/ed25519-signature-2020/issues/8

**Comment by tc-developer01** [comment]
Thank you for your response.

I've tried implementing the workaround described in the issue by adding
```
"transformIgnorePatterns": [
    "/node_modules/@digitalbazaar/bitstring/.+\\.js"
],
"moduleNameMapper": {
    "@digitalbazaar/bitstring": "@digitalbazaar/bitstring/main.js"
},
```

to the jest config, but now, instead of `bitstring_1.default is not a constructor`, I get the following error when trying to import Bitstring directly:

```
    [...]/node_modules/@digitalbazaar/bitstring/main.js:4
    import base64url from 'base64url-universal';
    ^^^^^^

    SyntaxError: Cannot use import statement outside a module
```

Apparently, Bitstring is not treated as a module this way anymore and cannot import sub-modules (like `base64url`) itself.

And this is still only having an effect when importing a Bitstring directly. It does not have an effect on the import inside the `vc-revocation-list`, where I still get the `Bitstring is not a constructor` message when calling `createList`.

My TypeScript / node knowledge is unfortunately too limited to understand how to properly include your JavaScript libraries in a somewhat clean and working way. 😕

**Comment by dlongley** [comment]
This looks to be another issue related to esm.js which was removed a while back. Closing.
