### ISSUE TITLE
ReferenceError: Cannot access 'CONTEXTS' before initialization

### ISSUE THREAD

**Issue by OR13** [digitalbazaar/vc-revocation-list#4]
guessing from tests about how to use this, encountering this error.

❯ node -v
v12.16.0

**Comment by OR13** [comment]
This is probably related to how node handles scoping require vs import.... I am able to fix this by moving the context defintion into the function which is exported...

```
export async function createCredential({id, list}) {
  const encodedList = await list.encode();
  const CONTEXTS = {
    VC_V1: 'https://www.w3.org/2018/credentials/v1',
    RL_V1: 'https://w3id.org/vc-revocation-list-2020/v1'
  };
  
  return {
    '@context': [CONTEXTS.VC_V1, CONTEXTS.RL_V1],
    id,
    type: ['VerifiableCredential', 'RevocationList2020Credential'],
    credentialSubject: {
      id: `${id}#list`,
      type: 'RevocationList2020',
      encodedList
    }
  };
}
```

I suggest making these contexts configurable... anywhere w3id.org is hardcoded, there is an extensibility issue, since developers will need to hack the document loader to add properties there... instead of just saying "https://example.com/ethereum/vc-revocation-list-2020/v1" has definitions about ethereum lists... etc... hard coding a context is equivalent to saying that you must be a member of a github organization to extend the credential format.

**Comment by dlongley** [comment]
Closing as old -- looks to either be invalid, addressed in some way already, or won't fix.
